# Set default wallpaper (leave monitor blank for all monitors)
wallpaper {
    monitor = DP-2
    path = ~/.config/wallpapers/wp11342455-evergreen-forest-wallpapers.jpg
    fit_mode = cover
}

splash = false

