# Set default wallpaper (leave monitor blank for all monitors)
wallpaper {
    monitor = eDP-1
    path = ~/dotfiles/walls/everforest/everforest2_1920x1200.jpg
    fit_mode = cover
}

splash = false

