return {
	"https://www.github.com/lewis6991/gitsigns.nvim",
	"https://www.github.com/echasnovski/mini.nvim",
	"https://www.github.com/ibhagwan/fzf-lua",
	"https://www.github.com/nvim-tree/nvim-tree.lua",
	{
		src = "https://github.com/nvim-treesitter/nvim-treesitter",
		branch = "main",
		build = ":TSUpdate",
	},
	"https://www.github.com/neovim/nvim-lspconfig",
	"https://github.com/mason-org/mason.nvim",
	"https://github.com/creativenull/efmls-configs-nvim",
	{
		src = "https://github.com/saghen/blink.cmp",
		version = vim.version.range("1.*"),
	},
	"https://github.com/L3MON4D3/LuaSnip",
	"https://github.com/ellisonleao/gruvbox.nvim",
	"https://github.com/ribru17/bamboo.nvim",
	"https://github.com/bjarneo/aether.nvim",
	"https://github.com/bjarneo/ethereal.nvim",
	"https://github.com/bjarneo/hackerman.nvim",
	{
		src = "https://github.com/catppuccin/nvim",
		name = "catppuccin",
	},
	"https://github.com/sainnhe/everforest",
	"https://github.com/kepano/flexoki-neovim",
	"https://github.com/rebelot/kanagawa.nvim",
	"https://github.com/tahayvr/matteblack.nvim",
	"https://github.com/loctvl842/monokai-pro.nvim",
	"https://github.com/EdenEast/nightfox.nvim",
	{
		src = "https://github.com/rose-pine/neovim",
		name = "rose-pine",
	},
	"https://github.com/folke/tokyonight.nvim",
	"https://github.com/folke/which-key.nvim",
	"https://github.com/nvim-tree/nvim-web-devicons",
	"https://github.com/nvim-lualine/lualine.nvim",
}

